/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App

fun main() {
    val d = Define()
    d.define("A", "(lambda(x) x)")
    // println(d.asignada("A"))

    val b = Define()
    b.define("hola", 3)
    val c = Comparador()
    println(b.asignada("hola"))
    val tokenizador: Tokenizador = TokenizadorSimple()

    val codigo = "(define fact (lambda (n) (if (equal? n 0) 1 (* n (fact (- n 1))))))"
    // val tokens = tokenizador.tokenizar(codigo)

    // println(tokens)
}
